[SPARK-37871][TESTS] Use `python3` instead of `python` in BaseScriptTransformation tests
### What changes were proposed in this pull request?

This PR aims to use `python3` instead of `python` in `BaseScriptTransformation` tests.

### Why are the changes needed?

Since Apache Spark deprecated `Python 2`, this PR aims to make it sure.

In addition, sometimes `python3` or `python3.x` command exists.
```
[info] - SPARK-25158: Executor accidentally exit because ScriptTransformationWriterThread throw Exception *** FAILED *** (248 milliseconds)
[info]   "Job aborted due to stage failure: Task 0 in stage 2162.0 failed 1 times, most recent failure: Lost task 0.0 in stage 2162.0 (TID 2627) (0ac7628d09c6 executor driver): org.apache.spark.SparkException:
Subprocess exited with status 127.
Error: /bin/bash: python: command not found
```

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Pass the CIs.

Closes #35171 from dongjoon-hyun/SPARK-37871.

Authored-by: Dongjoon Hyun <dongjoon@apache.org>
Signed-off-by: Dongjoon Hyun <dongjoon@apache.org>